package it.polimi.ingsw.gc03.view.ui.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN_USE,
    GAME_ID_NOT_EXISTS,
    ERROR_WHEN_ENTERING_GAME,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    NEXT_TURN,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED,
    PLACE_STARTER_ON_CODEX,
    DRAW_CARD,
    PLACE_CARD_ON_CODEX,
    CARD_CANNOT_BE_PLACED,
    POSITIONED_CARD,
    CHOOSE_OBJECTIVE_CARD,
    INVALID_COORDINATES,
    COMMON_CARDS_EXTRACTED

}
