package it.polimi.ingsw.gc03.view.flow.utilities.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN,
    GAME_ID_NOT_EXISTS,
    ERROR_WHEN_ENTERING_GAME,
    PLAYER_IS_READY_TO_START,
    COMMON_CARD_EXTRACTED,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    GRABBED_CARD,
    ASK_TO_SELECT_CARD_TO_PLACE,
    GRABBED_CARD_NOT_CORRECT,
    POSITIONED_TILE,
    NEXT_TURN,
    ADDED_POINT,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED

}
