package it.polimi.ingsw.gc03.view.flow.utilities.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN_USE,
    GAME_ID_NOT_EXISTS,
    ERROR_WHEN_ENTERING_GAME,
    PLAYER_IS_READY_TO_START,
    COMMON_CARD_EXTRACTED,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    POSITIONED_TILE,
    NEXT_TURN,
    ADDED_POINT,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED,
    PLACE_STARTER_ON_CODEX,
    DRAW_FROM_CHOSEN_DECK,
    PLACE_CARD_ON_CODEX,
    CARD_CANNOT_BE_PLACED,
    POSITIONED_CARD,
     CHOOSE_OBJECTIVE_CARD

}
